### ISSUE TITLE
[Feature request] display broken symlinks as such, don't abort. 

### ISSUE THREAD

**Issue by hillbicks** [ahupp/python-magic#103]
Hey guys,

I was wondering if it's possible to include a feature in a future release that is able to handle broken symlinks. Right now, if I'm parsing a broken symlink to magic it throws an 
```
OSError: File does not exist: and aborts.
```

It would be nice to just list that symlink as broken, similar to a symlink:

```
b'broken link to ../init.d/reboot'
```

Right now I'll catch this exception handing the file to magic, but it sure would be nice to have :)

**Comment by ahupp** [comment]
The `file` command actually does this:  

    adam@gaba:~$ ln -s foo bar
    adam@gaba:~$ file bar
    bar: broken symbolic link to foo

However, I'm hesitant to make a change like that:

-  for something that acts as a library this sounds like too much magic (hah!)
- it breaking backwards compatibility
- it's more likely to hide errors than prevent them

**Comment by Piraty** [comment]
there is an inconsistency in the library

this is how `file` works
```
$ ln -s foo bar
$ file bar
bar: broken symbolic link to foo

$ file --mime-type bar
bar: inode/symlink
```

using `file --mime-type` consistenly emits `inode/symlink`, regardless if the link is broken or nor (which i think is the right thing)

with `magic.from_file(foo, mime=true)` however, using it on broken symlinks raises `FileNotFoundError` ([from here](https://github.com/ahupp/python-magic/blob/067399b1ae104975fe83b5162dd3b83788cdfdd0/magic/__init__.py#L137-L138)) explicitly, which is not consistent with `file` and not conclusive as to what i asked the library to do
