### ISSUE TITLE
magic.from_buffer() swallows errors

### ISSUE THREAD

**Issue by dokai** [ahupp/python-magic#104]
Using libmagic version 5.26 (Macports libmagic@5.26_0) the following happens
```python
import magic
magic.from_buffer(b'<?xml version="1.0"?>', mime=True) is None  # -> True
```

In this `magic._magic_buffer` returns `None` which is recognized by `magic.errorcheck_null` which raises `magic.MagicException(b'Offset out of range')`. The try/except and the condition in `_handle509Bug` result in the exception to be ignored and `None` to be returned.

Is returning `None` the desired behavior or should a) the exception be allowed to propagate or b) an unconditional fallback value (`application/octet-stream`) be used instead? I'd prefer the public API to provide the means to handle and understand specific error conditions.

FWIW, I'm using Python version
```
3.5.1 (default, Mar  2 2016, 03:38:02)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

**Comment by dokai** [comment]
This seems to be a regression in `libmagic 5.26`. Version  `5.25` works as expected and returns `application/xml` for the testcase.

**Comment by ahupp** [comment]
I just pushed a fix for this to master.  Want to give it a try?
