### ISSUE TITLE
Using magic on 64bit Windows 10 with 64bit version of Python 2.7

### ISSUE THREAD

**Issue by ozgurakcali** [ahupp/python-magic#109]
In the above mentioned setup (everything 64bit), I am having trouble using the library. As noted in the Dependencies sections of the readme, I've donwloaded magic1.dll, regex2.dll, and zlib1.dss, copied them to a folder, and added that folder to path. Furthermore, I've copied the magic file from binary zip, and added %MAGIC% environment variable as mentioned in this SO answer: http://stackoverflow.com/a/28234688/843999

When I try to run my app with this setup, the process fails with the following message:

  import magic
  File "path\to\magic.py", line 150, in <module>
    libmagic = ctypes.CDLL(dll)
  File "c:\python27\Lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

How could it be fixed?

**Comment by ahupp** [comment]
This is addresses in the readme:

"'WindowsError: [Error 193] %1 is not a valid Win32 application': Attempting to run the 32-bit libmagic DLL in a 64-bit build of python will fail with this error. I'm not aware of any publically available 64-bit builds of libmagic. You'll either need to build them yourself (please share docs!), or switch to a 32-bit Python."

**Comment by jcannell** [comment]
Use this:

https://github.com/pidydx/libmagicwin64

**Comment by ahupp** [comment]
Thanks!
