### ISSUE TITLE
Create a VCS release for each actual release

### ISSUE THREAD

**Issue by benf-wspdigital** [ahupp/python-magic#111]
The VCS currently has only one release, “0.4.3”.

Please make a release (published at https://github.com/ahupp/python-magic/releases) corresponding to each release that has been made at PyPI.

This would ideally be part of the release procedure: tag the commit that represents the release; create a release in the VCS; publish that release to PyPI.

**Comment by ahupp** [comment]
Thanks, didn't remember to push tags.

**Comment by benf-wspdigital** [comment]
Thank you for the quick response!
