### ISSUE TITLE
Invalid magic file

### ISSUE THREAD

**Issue by drecker** [ahupp/python-magic#113]
Hi,
i have downloaded magic file from http://gnuwin32.sourceforge.net/packages/file.htm (downloaded "Binaries" file, unzip it, and use /share/misc/magic file). In my scipt i call:
```
mag = magic.Magic(magic_file=pkg_resources.resource_filename(__name__, 'magic')
```
(where `pkg_resources.resource_filename(__name__, 'magic')` is path to magic file from zip file as specified before), but it prints hundreds errors like:
```
avalens/magic, 362: Warning: string modifier `B' invalid
avalens/magic, 363: Warning: string modifier `B' invalid
avalens/magic, 364: Warning: string modifier `B' invalid
avalens/magic, 365: Warning: Current entry does not yet have a description for adding a MIME type
avalens/magic, 1009: Warning: Printf format `l' is not valid for type `belong' in description `%ld x'
avalens/magic, 1010: Warning: Printf format `l' is not valid for type `belong' in description `%ld'
avalens/magic, 1017: Warning: Printf format `l' is not valid for type `belong' in description `%ld x'

```
ending with error `MagicException: could not find any valid magic files!`

**Comment by ahupp** [comment]
There might be a compile step you need to do on the magic file.  I've not actually tried the setup on windows (all the docs are from 3rd parties) so i'm not sure of the details here.  If you find a solution let me know and I'll update.
