### ISSUE TITLE
Doesn't work if using musl libc: find_library is broken

### ISSUE THREAD

**Issue by thomwiggers** [ahupp/python-magic#114]
I'm trying to construct a Docker image based on Alpine Linux, which uses the musl libc implementation. There is an [existing issue in python](https://bugs.python.org/issue21622) that causes the `find_library` call to fail, which is rather unfortunate.

It's also reported [on the Docker image repository](https://github.com/docker-library/python/issues/111). It's not really an issue with this library I guess, but this report could be helpful to others coming here with the same issue.

**Comment by ahupp** [comment]
I'm not following the issue.  What would the fix look like?

**Comment by thomwiggers** [comment]
This issue is really the result of a bug in Python, but this library could work around it (although I'd understand it if you wouldn't want to).
I patched `magic.py` by making [line 150][L150] just return `libmagic.so.1`, but that is perhaps a bit messy. You could do what `ctypes.utils.find_library` should probably do: just look in `/usr/lib/` if `libmagic.so` exists.

[L150]: https://github.com/ahupp/python-magic/blob/master/magic.py#L150

**Comment by expl0ratory** [comment]
Is this package not maintained anymore?

**Comment by ahupp** [comment]
That function is a generator that produces candidate libraries, a the top
ever platform calls `find_library("magic")`:

https://github.com/ahupp/python-magic/blob/2a01b18ae0fe27e51977a54f0589910ddcc05804/magic/loader.py#L9

**Comment by thomwiggers** [comment]
Right, anyway, the quoted lines then indeed still tackle `musl`
