### ISSUE TITLE
No wheel for latest version 0.4.12

### ISSUE THREAD

**Issue by adamchainz** [ahupp/python-magic#118]
This project has `bdist_wheel` configuration in its `setup.cfg` but no wheel has been published. This implies that the `bdist_wheel` step was missed in release. A full sdist + bdist_wheel release can be done with `python setup.py clean sdist bdist_wheel upload`. You can also upload the wheel right now by checking out the source code at the version for the last release and running `python setup.py clean bdist_wheel upload`. This will speed up everyone's installs 🐇 😄

**Comment by eroen** [comment]
For a bit of context, the `bdist_wheel` stuff was added to `setup.cfg` *after* the 0.4.12 release.

**Comment by adamchainz** [comment]
Oh okay, then! I look forward to the 0.4.13 release...

**Comment by ahupp** [comment]
0.4.13 was uploaded, lmk if this works for you.

**Comment by adamchainz** [comment]
Wheel can be seen at https://pypi.org/project/python-magic/#files . Installing and importing works for me.

Thanks!
