### ISSUE TITLE
Some video files report to be audio files

### ISSUE THREAD

**Issue by deweydb** [ahupp/python-magic#119]
> import magic
> filePath = '/original_videos/i/Y/iYQaHvL8on3K6AmCxhnVP8VcoxnF2o36C0tWVZNnP5N.MP4'
> fileType = magic.from_file(filePath, mime=True)
> print 'file type:%s' % fileType

file type: audio/mp4

Example video file: https://uccdn.bid13.com/original_videos/i/Y/iYQaHvL8on3K6AmCxhnVP8VcoxnF2o36C0tWVZNnP5N.MP4

Is this intended behaviour?

**Comment by ahupp** [comment]
python-magic is a wrapper around libmagic.   That's responsible for all the file identification so I suggest asking there.
