### ISSUE TITLE
MagicException on getting description for ELF Executable

### ISSUE THREAD

**Issue by gurol** [ahupp/python-magic#122]
While getting a MIME type by providing mime=True in from_file returns application/x-executable.  Without this flag (i.e. getting textual description) causes exception with this message:

> ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker error reading (Inappropriate file type or format)

You may want to refer here for a solution: http://stackoverflow.com/a/8617852/2101864

My test file's hash is 3cab719708dd89405890dc9ae830a48c.

**Comment by ahupp** [comment]
This seems like an error with the underlying libmagic library.  I suggest reporting it to them via the mailing list found here: http://www.darwinsys.com/file/

**Comment by gurol** [comment]
I have submitted the issue as you told. Thanks.
