### ISSUE TITLE
How can I get mimetypes of a single python file? 

### ISSUE THREAD

**Issue by dogukankotan** [ahupp/python-magic#124]
>>> import magic
>>> magic.from_file("test.py")
text/plain

However, when I try something like that
>>> import mimetypes
>>> mimetypes.guess_type("test.py")
('text/x-python', None)

Second example can give me better solution. I want to use it in magic. 

Thanks

**Comment by dogukankotan** [comment]
Ok. I found a solution. I have to specify magic.mgc file. For example: magic_file='C:\Python27\magic.mgc'.

**Comment by ahupp** [comment]
I suspect "guess_type" depends just on the filename rather than any contents.
