### ISSUE TITLE
Unusual mime type strings for some libraries (CUDA)

### ISSUE THREAD

**Issue by s-m-e** [ahupp/python-magic#138]
I see some interesting behavior while checking mime types of some CUDA libraries, e.g. 

    cuda/NVIDIA_CUDA-6.5_Samples/7_CUDALibraries/common/FreeImage/lib/darwin/libfreeimage_10_6.a

I'll get an answers like this:

    ' [application/x-archive ['

The string containing squared brackets and spaces is actually returned like this by python-magic. Other lib files from CUDA produce the following variation: 

    ' [ [application/octet-stream'

Reading the sources, I am getting the feeling that this is a bug "further upstream" in libmagic, but I'd like to confirm.

**Comment by ahupp** [comment]
That does seem like a libmagic issue.  What does `file --mime-type` return?  Does this happen for all archive files, or just the CUDA ones?

**Comment by s-m-e** [comment]
I got in touch with the maintainer of file/libmagic (its [bug tracker](http://bugs.gw.com/) has been down for a few weeks now). He wants to look into it - the root cause appears to be in this library.

------------

There are two examples (with file -i/--mime-type):

1) [Option.class](http://www.schmidma.de/selfhtml/html/multimedia/anzeige/Option.class)

```
~> wget http://www.schmidma.de/selfhtml/html/multimedia/anzeige/Option.class
~> file -i Option.class
Option.class:  [ [application/octet-stream; charset=binary
```

It's a lot of java class files from a bunch of old compendium archives and class notes, which are mainly causing this particular string.

2) [libfreeimage.a](https://github.com/zchee/cuda-sample/raw/master/7_CUDALibraries/common/FreeImage/lib/darwin/libfreeimage.a)

```
~> wget https://github.com/zchee/cuda-sample/raw/master/7_CUDALibraries/common/FreeImage/lib/darwin/libfreeimage.a
~> file -i libfreeimage.a
libfreeimage.a:  [application/x-archive [; charset=binary
```

This one seems to be exclusive to (all) library files for MaxOS in the CUDA examples collection.

**Comment by ahupp** [comment]
Since this seems to be in libmagic and you've engaged with them, I'm closing out.
