### ISSUE TITLE
CPU loop (Python 2.7.8 on Windows 7 and 10)

### ISSUE THREAD

**Issue by codingatty** [ahupp/python-magic#140]
I initially encountered this as an [apparent issue with eyed3](https://github.com/nicfit/eyeD3/issues/84), but have been able to isolate it to magic, which is used by eyed3.

Python script calling magic is non-responsive, even to a CTRL-C; Process Explorer sees CPU to the python task go to nearly 25% (i.e., one core).

Simple script to reproduce:

```Python
import sys
print "OS info:\n ", sys.getwindowsversion()
print "Python info:\n ", sys.version
import magic
print "Calling magic..."
print magic.from_file("test.py")
print "returned from magic call."
```

Output:
```
OS info:
  sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
Python info:
  2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)]
Calling magic...
```
... at which point the script hangs, pegging CPU at ~25% (one of four cores), the call never completing. I can kill the Python task from Process Explorer.

based on some print statements, it appears to be hanging in ```class Magic```, ```__init__```, at the statement
```Python
self.cookie = magic_open(self.flags)
```

**Comment by ahupp** [comment]
python-magic is a wrapper around libmagic, which is a C library.  You'd need to attach a debugger and see where it's hanging in there.  Just a random guess, but could you have a malformed db file?

**Comment by codingatty** [comment]
Possible, but unlikely, given that the same error occurs on two different systems. The Cygwin `file` command-line utility, which I think relies on the db, seems to work okay.

I just did a Cygwin refresh, updating the `file` package (which includes the cygmagic-1.dll) from 5.25-1 to 5.30-1, but no joy.

I don't claim to know what I'm doing when it comes to ctypes, but fumbling around based on the magic.py module, can reproduce the error with just this:

```Python
import ctypes
import ctypes.util
from ctypes import c_char_p, c_int, c_size_t, c_void_p

dll = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1') or ctypes.util.find_library('cygmagic-1')

print dll # prints C:\bin\cygwin\bin\cygmagic-1.dll
libmagic = ctypes.CDLL(dll)
magic_open = libmagic.magic_open
magic_open.restype = c_void_p
magic_open.argtypes = [c_int]
print "going for it"
cookie = magic_open(0x000000)
print "back"
```

When it comes to trying to debug a dll binary, I'm well out of my depths, so I may be hosed.

I'm surprised I get this on two different systems, though, and no one else does.

**Comment by ahupp** [comment]
That is mysterious.   Could you try writing a small C program that links against cygmagic and calls magic_open?  That would at least give an idea of it's in ctypes/python or in libfile.

**Comment by codingatty** [comment]
Bearing in mind I really don't know C very well, or for that matter ctypes, I hacked together the following through trial-and-error...

```C
#include <stdio.h>
#include <magic.h>

int main()
{
  const char *filename = "testit.c";
  const char *results;
  printf("trying magic_open...\n");
  magic_t myt = magic_open(0);
  printf("back from magic_open.\n");
  magic_load(myt,NULL);
  results =  magic_file(myt, filename);
  printf("magic output: '%s'\n", results);
  magic_close(myt);
  return 0;
}
```

This prints:
```
trying magic_open...
back from magic_open.
magic output: 'C source, ASCII text, with CRLF line terminators'
```

Python equivalent, just through the magic_open call:

```Python
import ctypes
import ctypes.util

dll = ctypes.util.find_library('cygmagic-1')
print dll # prints C:\bin\cygwin\bin\cygmagic-1.dll
libmagic = ctypes.CDLL(dll)
magic_open = libmagic.magic_open
magic_open.restype = ctypes.c_void_p
magic_open.argtypes = [ctypes.c_int]

filename = "testit.c"
print "trying magic_open..."
cookie = magic_open(0x00000000)
print "back from magic_open."

# code to invoke magic_load and magic_file would go here```

produces:
```
C:\bin\cygwin\bin\cygmagic-1.dll
trying magic_open...
```

and hangs.

Clearly, I've got a ctypes problem here, not with magic.py.

Both my Python installation and Cygwin installation are 32-bit.

**Comment by ahupp** [comment]
Hmm, interesting.  Are you using the python build from cygwin, or a different one?  If different, does the cygwin python work?

**Comment by ahupp** [comment]
"Both my Python installation and Cygwin installation are 32-bit."

Ah this was one of my guesses but it usually doesn't manifest this way.  

Maybe procmon will help?  https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

This is will tell you what other DLLs are being loaded, where they are coming from, maybe there's some file IO failing, etc.

**Comment by codingatty** [comment]
I'm using Activestate Python, not the cygwin one. When I try the Cygwin one, I get even odder errors, "AttributeError: function 'magic_open' not found". I'm guessing that that's probably something where the Cygwin Python is probably picking up stuff from the Activestate Python's PYTHONPATH or something,though, so I'm not sure that that's meaningful.

I don't see anything obvious from the procmon data, but I really don't know how to interpret it, either.

I would go to the latest Activestate Python, but it looks like they don't do 32-bit any longer. I cannot recall the reason, but there was some reason where I needed to use 32-bit for both Python and Cygwin for some sort of compatibility.

**Comment by codingatty** [comment]
Okay, as it turns out, the AttributeError in cygwin Python was only because the ```find_library('cygmagic-1')``` call that worked from ActiveState Python didn't work from Cygwin's. Cygwin finds ```cygmagic-1.dll``` with ```find_library('magic')``` (not sure I understand that, but, okay). It wasn't a PYTHONPATH issue at all.

Anyway, using the Cygwin Python, it works:
```Python
import ctypes
import ctypes.util

dll = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1') or ctypes.util.find_library('cygmagic-1')
print dll # prints cygmagic-1.dll
libmagic = ctypes.CDLL(dll)
magic_open = libmagic.magic_open
magic_open.restype = ctypes.c_void_p
magic_open.argtypes = [ctypes.c_int]


magic_load = libmagic.magic_load
magic_load.restype = ctypes.c_int
magic_load.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

magic_file = libmagic.magic_file
magic_file.restype = ctypes.c_char_p
magic_file.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

filename = "testit.c"
print "trying magic_open..."
cookie = magic_open(0x00000000)
print "back from magic_open."
magic_load(cookie, None)
results = magic_file(cookie, filename)
print "magic output: '%s'" % results    
```
yields:
```
cygmagic-1.dll
trying magic_open...
back from magic_open.
magic output: 'C source, ASCII text, with CRLF line terminators'
```

So this means my problem is really with whether ActivePython ctypes can be made to work with a Cygwin DLL (I have another program I wrote that works with a Windows DLL, so I know ctypes does work  at least there).

Anyway, at this point, it's pretty clearly not an issue with magic.py (that was clear a few hours ago, really, when I reproduced it with ctypes alone). I'll try a few more things and maybe see if anyone on stackoverflow has any ideas. Worst comes to worst, I only have one program that uses eyeD3 and magic, so I can use a simple batch file to force that to use the Cygwin Python, so I have a workaround now. Thanks for your attention and ideas here.

**Comment by codingatty** [comment]
Just wanted to close the loop on this. I had planned to go to the most recent 32-bit version of ActiveState Python, but they have dropped 32-bit.  Although I know I had some reason to require 32-bit instead of 64-bit, I can no longer remember what it was, so maybe it doesn't apply any longer, so I bit the bullet and installed 64-bit ActiveState Python; then also went to 64-bit Cygwin.

I no longer get the loop, but now get the symptoms as described in Issue #24 ; although the solution suggested there does not work.

Using the (now 64-bit) python included in Cygwin continues to work, and that provides me a good enough workaround. I am guessing that there's probably some mismatch between the <code>MSVCP*.DLL</code> file used by Activestate Python and Cygwin, but don't really know. I'm just leaving this message so that, if future users come to you with an issue under Activestate Python, you're aware of the issue. (In fairness to Activestate, I could have gone to their support forum and opened an issue there; but I'm happy enough with my workaround.)

Thanks once again for the assist, even after it was clearly not an issue with magic.

Just so you have it, here is the bare working test case, the one that works under Cygwin Python and fails under ActivestatePython:

```Python
import ctypes
import ctypes.util

print __file__

dll = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1') or ctypes.util.find_library('cygmagic-1')
print dll 
libmagic = ctypes.CDLL(dll)
magic_open = libmagic.magic_open
magic_open.restype = ctypes.c_void_p
magic_open.argtypes = [ctypes.c_int]


magic_load = libmagic.magic_load
magic_load.restype = ctypes.c_int
magic_load.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

magic_file = libmagic.magic_file
magic_file.restype = ctypes.c_char_p
magic_file.argtypes = [ctypes.c_void_p, ctypes.c_char_p]

filename = __file__
print "trying magic_open..."
cookie = magic_open(0x00000000)
print "back from magic_open."
magic_load(cookie, None)
results = magic_file(cookie, filename)
print "magic output: '%s'" % results   
```

Under Cygwin Python I get:
```
CygPyTest.py
cygmagic-1.dll
trying magic_open...
back from magic_open.
magic output: 'ASCII text, with CRLF line terminators'
```
Under Activestate Python (64-bit now) I get:
```
E:\test\ctypeTest\CygPyTest.py
C:\windows\system32\magic1.dll
Traceback (most recent call last):
  File "E:\test\ctypeTest\CygPyTest.py", line 8, in <module>
    libmagic = ctypes.CDLL(dll)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```
