### ISSUE TITLE
Please exempt "magic.pyc" test file from cleaning, or rename it

### ISSUE THREAD

**Issue by cbiedl** [ahupp/python-magic#141]
Hello,

the test data directory contains a file "magic.pyc". Some build systems run "clean" on the source tree, and compiled python files are removed during such an operation - which in general is the right thing but undesired here since subsequently the test suite will fail for a missing file.

Please find a solution for this - either by signalling this file shall be exempted from clean, if possible. Or by renaming it. The latter is certainly easier to do.

**Comment by ahupp** [comment]
fixed in cf029d7cb3786754d35194fbbdc870e8f54711cd
