### ISSUE TITLE
"keep-going" test broken

### ISSUE THREAD

**Issue by cbiedl** [ahupp/python-magic#142]
Hello,

the test suite fails:

  ======================================================================
  FAIL: test_keep_going (test.test.MagicTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/src/cbiedl/debian-playground/sid/main/python-magic/python-magic.git/test/test.py", line 88, in test_keep_going
      self.assertEqual(m.from_file(filename), 'image/jpeg')
  AssertionError: 'image/jpeg\\012- application/octet-stream' != 'image/jpeg'
  

This was introduced by a change in file between 5.22 and 5:23:

  commit f4481bdba01ddc1e5d834cd98b04ebf95af9b02b (FILE5_22-70-gf4481bdb)
  Author: Christos Zoulas <christos@zoulas.com>
  Date:   Thu May 28 19:26:59 2015 +0000
  
      Honor MAGIC_CONTINUE for all kinds of magic tests

**Comment by ahupp** [comment]
Thanks for the report.  This is fixed in 9d127ceaab1da0632128422ffd6a2d340bd3e778.

**Comment by ahupp** [comment]
I don't love the lack of backwards compatability in libmagic here.
