### ISSUE TITLE
Please clarify test/testdata/keep-going.jpg license

### ISSUE THREAD

**Issue by cbiedl** [ahupp/python-magic#143]
Hello,

the test/testdata/keep-going.jpg file is a photo that probably was taken by Slava Stepanov <https://gelio.livejournal.com/profile>, and I'm a bit confused about the licensing situation. At least, it's not quite obvious the MIT license of python-magic applies to this file as well.

To clarify, can you please add a notice in your LICENSE file about the situation?

**Comment by ahupp** [comment]
The file was submitted by the original bug reporter, and tbh I never even looked at what was in it.  I guess it's a good thing it wasn't inappropriate.  I've replaced this with my own photo in 8be47895bc108394c76badd74c0f681f6d5da63e.
