### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by CarlGalloy** [ahupp/python-magic#145]
Hi.
In dependency section mention that "magic1.dll, regex2.dll, and zlib1.dll onto your PATH from the Binaries  " where exactly PATH is? ( System Environment PATH? )

**Comment by ahupp** [comment]
Yes, your %PATH% environment variable.

**Comment by CarlGalloy** [comment]
Now i have this Error:

``
>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\magic.py", line 154, in <module>
    libmagic = ctypes.CDLL(dll)
  File "C:\Python27\lib\ctypes\__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
``

I install python-magic using `pip install magic-python` and i can see files on python`site-packages` installation directory.

What's wrong?
and a question: : we must pass location of `magic` file (from `[binary-zip]\share\misc` ) to `Magic(magic_file=...)` ? Like this below code?

``
f = magic.Magic(mime=True, uncompress=True,magic_file="./mymagicfile/magic")
``

**Comment by ahupp** [comment]
No, the magic_file argument won't help here.  It's failing to load the libmagic dll for some reason.  I generally like to use the "Process Monitor" utility from sysinternals to figure out where it's trying to load DLLs from.  Either it's looking in the wrong place, or there's a missing dependency of those dlls.

**Comment by Ayla93** [comment]
Is the problem solved?

**Comment by ahupp** [comment]
@Ayla93: to be clear, this is a local install issue rather than a bug in the library.  Are you seeing the same issue as @CarlGalloy ?

**Comment by theirfanirfi** [comment]
Where is the magic1.DLL and regex located in windows 10. I'm having the same import error. 
Please help me out.

**Comment by ahupp** [comment]
Those are 3rd party libraries you'll have to install.   The README file includes some pointers to them, and I've updated it with more info.

**Comment by ysinjab** [comment]
For me i faced this issue when I import magic library in my django application. I solved it by " brew install libmagic" installing libmagic on the system level

**Comment by ashishnitinpatil** [comment]
I had this issue with official python docker (python:3.7-slim-buster), so I fixed it with `apt-get install libmagic-dev`.

**Comment by jppg** [comment]
I solve this problem with "pip install python-magic-bin"

**Comment by ye** [comment]
Yep, @ashishnitinpatil your comment was very helpful. The official python docker images is missing the (libmagic-dev for [Debian based distro](https://packages.debian.org/sid/amd64/libmagic-dev/filelist), headers, aka dynamic libraries files etc.), so we need to install `libmagic-dev` to make it work during the runtime (magic checks the dynamic libs). Alternatively, include the `python-magic-bin` version which includes those required files.
