### ISSUE TITLE
AssertionError: 'image/jpeg' != 'image/jpeg\\012- application/octet-stream'

### ISSUE THREAD

**Issue by hugovk** [ahupp/python-magic#148]
The build has been failing since the assert change in https://github.com/ahupp/python-magic/commit/9d127ceaab1da0632128422ffd6a2d340bd3e778 and the code still returns the old value.

```
======================================================================
FAIL: test_keep_going (test.test.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ahupp/python-magic/test/test.py", line 90, in test_keep_going
    self.assertEqual(m.from_file(filename), 'image/jpeg\\012- application/octet-stream')
AssertionError: 'image/jpeg' != 'image/jpeg\\012- application/octet-stream'
----------------------------------------------------------------------
```

Should that commit be reverted? Or something else changed in code so it returns the new value?

**Comment by ahupp** [comment]
Thanks for flagging.  I was hoping to fix the Travis build but it turned out to require more digging into docker than I had time to do.  I've pulled your revert.
