### ISSUE TITLE
cannot open include file: 'magic.h'

### ISSUE THREAD

**Issue by sc4224** [ahupp/python-magic#151]
hi, i'm using python 3.5 64bit that runs on windows 10 64bit.

so i understand that i need to include both DLL files in Windows/System32.
then in my project that references the magic module, I need to reference the path to the magic.mgc file. However when I do that, the command prompt still gives me this error "cannot open include file: 'magic.h'

This is what the reference looks like
`
import magic
`
`
file_magic = magic.Magic(magic_file="C:\\Users\\Shaun Chua\\Documents\\libmagicwin64\\magic.mgc")
`
`
if not file_magic.from_buffer(f.read(1024), mime=True).startswith('text/'):
`

**Comment by ahupp** [comment]
Can you paste the specific error?  That's very mysterious.  In general this library is a thin wrapper around libmagic and this error is coming from there.

**Comment by ahupp** [comment]
This is a different package that uses the same module name.  You need to uninstall python-libmagic and install python-magic.
