### ISSUE TITLE
from_buffer() reports incorrect mimetype/desc for python3

### ISSUE THREAD

**Issue by rene00** [ahupp/python-magic#152]
The code below works as expected with python2.

```
import magic
script = '#!/usr/bin/env python\nprint("foo")'
print(magic.from_buffer(script, mime=True))
```

```
$ python2 tmp/t.py 
text/x-python
```

Though I get back something different with python3.

```
$ python3 tmp/t.py 
application/octet-stream
```

`from_file()` returns the correct mimetype/desc for python3 though.

**Comment by ahupp** [comment]
This is pretty bad.  It looks like ctypes in python3 passes a wchar* to functions taking char*, which (I guess?) means each 16-bit character looks like [ascii, null, ascii, null, etc] or something like that.  
```

>>> import ctypes, ctypes.util
>>> libc = ctypes.CDLL(ctypes.util.find_library("c"))
>>> libc.strlen("hello")
1
>>> libc.strlen(b"hello")
5
>>>

```
And for some reason libmagic seems to handle this just fine most of the time anyways.  It even handles it for a non-mime call on this string.

I've fixed this in bec0d4428f6de11ffd90d19dfddb5af9c72d9c63

**Comment by ahupp** [comment]
This is pretty bad.  It looks like ctypes in python3 passes a wchar* to functions taking char*, which (I guess?) means each 16-bit character looks like [ascii, null, ascii, null, etc] or something like that.  
```

>>> import ctypes, ctypes.util
>>> libc = ctypes.CDLL(ctypes.util.find_library("c"))
>>> libc.strlen("hello")
1
>>> libc.strlen(b"hello")
5
>>>

```
And for some reason libmagic seems to handle this just fine most of the time anyways.  It even handles it for a non-mime call on this string.

I've fixed this in bec0d4428f6de11ffd90d19dfddb5af9c72d9c63

**Comment by ahupp** [comment]
libmagic's python bindings has the same bug.

**Comment by ahupp** [comment]
This was fixed a long time ago.
