### ISSUE TITLE
AttributeError: module 'magic' has no attribute 'from_file'

### ISSUE THREAD

**Issue by francesco1119** [ahupp/python-magic#153]
I receive an error in Python3 that I don't have in Python2

This is my code:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import magic
import os
import os.path

# Argparse starts here
parser = argparse.ArgumentParser()								
parser.add_argument('-input', dest='input',help="input one or more files",metavar=None)
args = parser.parse_args()

input = args.input
file = magic.from_file(input)
print (file)
```

I run it on python and everything works fine: it correctly recognize a TXT file
![fine_python2](https://user-images.githubusercontent.com/3397477/33502928-d3699530-d746-11e7-8470-68c41a778ef1.PNG)
I run it on Python3 and the code doesn't work: it trow the error

`AttributeError: module 'magic' has no attribute 'from_file'`

![notfine_python3](https://user-images.githubusercontent.com/3397477/33502954-e75745e2-d746-11e7-9f62-a5e0c7d32c56.PNG)
for both version python-magic is installed even if, strangely, they both looks installed under
`/usr/local/lib/python3.5 `
![both_for_python3](https://user-images.githubusercontent.com/3397477/33503073-44dc3a06-d747-11e7-9f8a-fd1890f248af.PNG)
My Python versions are;
![versions](https://user-images.githubusercontent.com/3397477/33503114-5d169f80-d747-11e7-9da7-200a7e7643ae.PNG)

**Comment by ahupp** [comment]
What does `magic.__file__` report?  I'm guessing you have a different module with that name in your PYTHONPATH.

**Comment by francesco1119** [comment]
You fixed my tralala:

`pip uninstall python-libmagic`

was the solution! Thank you so much!!!

**Comment by FabioNevesRezende** [comment]
I'm also having this issue however uninstalling python-libmagic didn't solved.
Also

> Python 3.7.3 (default, Jun 24 2019, 22:30:13) 
> [GCC 9.1.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import magic
> >>> magic.__file__
> '/usr/lib/python3.7/site-packages/magic/__init__.py'

**Comment by ahupp** [comment]
What is the contents of that __init__.py file?  Can you run `magic.from_file` in that same interpreter session to verify the process w/ the error is seeing that same module?
