### ISSUE TITLE
GitHub vs PyPI release version

### ISSUE THREAD

**Issue by christiankossmann** [ahupp/python-magic#157]
On the GitHub release page the latest release is 0.4.14 and on PyPI it it 0.4.15. Are there any differences between these two versions?

Apart from that, is it possible to upload the sources of the 0.4.15 release to PyPI?

**Comment by ahupp** [comment]
Forgot to tag it.  I've tagged and uploaded source.

**Comment by christiankossmann** [comment]
Thanks a lot!
