### ISSUE TITLE
[wishlist] dereference option to from_file

### ISSUE THREAD

**Issue by yarikoptic** [ahupp/python-magic#159]
Similarly to `file` command having `--dereference` it might be useful to have a little sugaring of `dereference=False` option for `from_file` which would call to `os.path.realpath(filename)` first

**Comment by ahupp** [comment]
5 years later, I added a follow_symlink flag to magic.Magic() in 2a01b18ae0fe27e51977a54f0589910ddcc05804.  Sorry for the wait!
