### ISSUE TITLE
zip/rar format's recognized as "application/octet-stream"

### ISSUE THREAD

**Issue by aa66609** [ahupp/python-magic#166]
i test zip,rar file got these result

---------------------------------------------
magic.from_file('test.zip', mime=True)
application/octet-stream

magic.from_file('test.rar', mime=True)
application/octet-stream

---------------------------------------------

but z01 is ok 
magic.from_file('test.z01', mime=True)
application/zip

**Comment by ahupp** [comment]
This is most likely the underlying libmagic libary.

**Comment by ahupp** [comment]
What does this report?

  file --mime-type <the file>

**Comment by eumiro** [comment]
@ahupp maybe that discussion in https://github.com/destream-py/destream/pull/20 could have something to do with it. There are different versions of ZIP and they are differently interpreted on different linux/macos versions. Any ideas?

**Comment by ahupp** [comment]
@eumiro I commented there.  Looks like maybe the magic db didn't set the mimetype for this new format.  But might be fixed in a newer version.

**Comment by ahupp** [comment]
Old issue, and is a problem in libmagic.
