### ISSUE TITLE
mp3 files are not detected by python magic library

### ISSUE THREAD

**Issue by sezal98** [ahupp/python-magic#167]
import magic
magic.from_file("tests/test.pdf")
# 'PDF document, version 1.2'
magic.from_file("tests/song.pdf")
# 'data'
magic.from_file("tests/song.mp3")
# 'data'
magic.from_file("tests/images(3).jpg")
# 'JPEG image data, JFIF standard 1.01'

here test file is an pdf document, image is a jpg doc .. however song is an mp3 doc. even when i rename the song file to song.pdf it gives an output of DATA and even in mp3 it gives and output of DATA.

**Comment by ahupp** [comment]
These are generally issues in the underlying libmagic library.  Do you get different results with mime=True?  What does the command-line `file` command report?

**Comment by ahupp** [comment]
No response from submitter, closing.  Feel free to re-open if you have more issues.
