### ISSUE TITLE
Suggestion for an improved test run.sh test script (script attached)

### ISSUE THREAD

**Issue by Corin-EU** [ahupp/python-magic#168]
The current test run.sh test script tries to run python executables even if they are not available and the script is not flexible for testing multiple versions of python if they are available.

Please find attached a suggestion for an improved shell script for which testing against officially supported versions can easily be changed by editing the values of the variables PYTHON2_VERSIONS and PYTHON3_VERSIONS, and which also tests against major version numbers for completeness.

The test for each version is only run if the python version is found in the current ${PATH} environmental variable which is checked by means of the Bourne shell "command" builtin + "-v" option.

suggested improved test/run.sh Bourne shell script:
[run.sh.txt](https://github.com/ahupp/python-magic/files/2087310/run.sh.txt)

**Comment by ahupp** [comment]
Hi Corin, thanks for the suggestion.  I've adapted this a bit and pushed it as 6102e9f.  BTW, it's easier for me if you submit changes as pull requests rather than raw files.
