### ISSUE TITLE
Why do I get an IsADirectory exception when evaluating directories?

### ISSUE THREAD

**Issue by biggieAl** [ahupp/python-magic#170]
On my linux box if I run "file" against an entire directory I get the file types identified as well as directories being categorized as such.  With magic I have to check to see if a file is actually a directory before I make a call or else I get an exception.

**Comment by ahupp** [comment]
libmagic itself returns an error when run on a directory.  It's up to the application (like `file`) to decide how to handle directories, but I generally I'd consider it an error to pass one in to from_file.
