### ISSUE TITLE
Test suite breakage with recent file/libmagic version

### ISSUE THREAD

**Issue by cbiedl** [ahupp/python-magic#173]
As reported in <https://bugs.debian.org/897471>, the python-magic test suite breaks when handling "test.gz". The actual reason is in libmagic - it required some digging to understand magic_file() on a file name and magic_buffer on a buffer loaded from that particular file may return a different result, just because the first is a file.

magic_file() result:
gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix, original size 15

magic_buffer result:
gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix

At first, it would have been easier to find this if test.py would have reported a difference in the first place. Perhaps something like the following?

@@ -26,6 +26,11 @@ class MagicTest(unittest.TestCase):
                     buf_value = m.from_buffer(f.read())
 
                 file_value = m.from_file(filename)
+                if buf_value != file_value:
+                    print("from_buffer: '" + buf_value + "'")
+                    print("from_file:   '" + file_value + "'")
+                    self.assertTrue(False, "from_buffer from_file output mismatch")
+                    break

Also, for the time being I suggest to disable that particular test, or to work around it in a sane way. Also, don't forget to add the new output to the list of possible results.

Regards,

    Christoph

**Comment by cbiedl** [comment]
The differing output between magic_file() and magic_buffer() is now (5.34) a documented behavior, see doc/libmagic.man. Therefore, an adjustment in your test is inevitable now.

**Comment by sbraz** [comment]
Looks like the update to the manpage update isn't in 5.34 yet: https://github.com/file/file/commit/d63f218352622b74e8a323a9177e612c947ce848

**Comment by ahupp** [comment]
Thanks for the report, this was fixed in #177.
