### ISSUE TITLE
Typing stub file

### ISSUE THREAD

**Issue by aaronjeline** [ahupp/python-magic#174]
Is there a stub file for the new python typing features available?

**Comment by ahupp** [comment]
There is not one available, but would be happy to include if someone write it up.

**Comment by RJPercival** [comment]
For this to actually work, you need to include a file named `py.typed` in the package. See [PEP-561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information).

**Comment by ahupp** [comment]
@RJPercival: thanks, does 29450ec911b08dc2b128fa00cd95cf6ba27bccdc look correct?  How do you test it?

**Comment by RJPercival** [comment]
`package_data` is supposed to be a dict with the key being the package name I think. You can test it by simply importing magic into another project and running mypy on that project with the default settings (crucially, the `ignore_missing_imports` mypy setting should be false, which is the default). It'll error if the `py.typed` file isn't detected.

**Comment by ahupp** [comment]
This is fixed in 0.4.23, I verified with a sample project.  Thanks @RJPercival !
