### ISSUE TITLE
AttributeError: module 'magic' has no attribute 'MAGIC'

### ISSUE THREAD

**Issue by cmorris2945** [ahupp/python-magic#175]
I keep getting this error message from the library magic in python. I know I installed magic through command line. I am running windows 10 through anaconda navigator.

import phate
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import LocallyLinearEmbedding

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D, get_test_data
from matplotlib import cm
import numpy as np
import magic

#import the dataset
myData = pd.read_csv(r'C:\Users\chris\Desktop\DATA_SCIENCE\EMLG\PICTURE_RESULTS\EMLG.csv', index_col = 0)
del myData["mgenes"]

#T = transpose to flip columns and rows PhATE expects genes on columnn and  cells on rows
myData = myData.T

librarySize = myData.sum(axis = 1)       
           
plt.hist(librarySize, bins = 100)    
np.min(librarySize)

#We don't have to actually do this. This is just a filtering method
#myData = myData.loc[librarySize > 2000]       
           
myData = phate.preprocessing.library_size_normalize(myData)           

myData = np.sqrt(myData)

#You could run this 2 dimensiona and 3 dimensions
phate_Op = phate.PHATE(n_components = 3)

myData_phate = phate_Op.fit_transform(myData)
phate.plot.scatter2d(myData_phate)

phate.plot.scatter3d(phate_Op)

# this creates rotating 3D plot  You need to install "FFMPEG" or "imagemagick"
#phate.plot.rotate_scatter3d(phate_Op, filename = "3DExample.mp4")
phate.plot.rotate_scatter3d(phate_Op, c=myData_magic['ENSMUSG00000048047\tZbtb33'], filename="phate2_colored_by_...._magic.gif")
for i, gene in enumerate(myData.columns):
    if gene.endswith("Zbtb33"):
        print(i)
myData.columns[4356]    
    
    
    
magic_Op = magic.MAGIC()
myData_magic = magic_Op.fit_transform(myData, genes = ['ENSMUSG00000048047\tZbtb33'])
phate.plot.scatter3d(phate_Op, c = myData["ENSMUSG00000048047\tZbtb33"], figsize = (14, 12))

phate.plot.scatter3d(phate_Op, c = myData_magic["ENSMUSG00000048047\tZbtb33"], figsize = (18, 16))

phate.plot.scatter2d(myData_phate, c = myData_magic["ENSMUSG00000048047\tZbtb33"],figsize = (14, 12))

#If you want to do all the genes
myData_magic = magic_Op.fit_transform(myData, genes = "all_genes")

**Comment by ahupp** [comment]
I think you intend to use this library: https://github.com/KrishnaswamyLab/MAGIC

That seems to be using the same `magic` module name as this one.  Maybe uninstall `python-magic` to avoid the conflict?

**Comment by mohamedelsaey** [comment]
> It's ok, I think I got it.

How did you solve this issue? Thanks!
