### ISSUE TITLE
Possibly do another release, including libmagic-compat branch

### ISSUE THREAD

**Issue by cbiedl** [ahupp/python-magic#180]
Severity: wishlist

Hi there,

it's been some time since the last release (0.4.15) which also predates the libmagic-compat branch. For Debian, I've picked that branch as an additional patch but since I prefer to keep patches small, a new upstream release would result in a smaller deviation.

You might be pleased to learn in the seven months since Debian switched to your libmagic Python bindings, not a single issue was reported. So it seems the compat methods were done very well.

Aside, there's a 0.4.16 release commit in that libmagic-compat branch - possibly in error, at least this does not show up in <https://github.com/ahupp/python-magic/releases>

Regards,

**Comment by cuixinye** [comment]
@ahupp It would be greate if you make a new release to pypi. You changed version number in source codes, but didn't tag it or release it to pypi.

**Comment by cbiedl** [comment]
One year later, gentle ping?

**Comment by 00willo** [comment]
Thanks for this package @ahupp . Just moved some code over to python3.8 and I'm getting lots of the SyntaxWarnings being thrown. With #187 being fixed, it'd be awesome if there was another release on pypi.

**Comment by ahupp** [comment]
Sorry for dragging my feet on this.  I'll push out a new release asap.

**Comment by SchoolGuy** [comment]
@ahupp Gentle ping again. This is currently breaking our Packaging - https://github.com/cobbler/cobbler/pull/2514

I could help with the Python part if you desire help in this direction.

**Comment by ahupp** [comment]
ASAP turned out to be 9 months, but 0.4.20 is out with the compat branch.  Thanks @SchoolGuy for the PR!

**Comment by cbiedl** [comment]
Don't tell me about the better-late-than-never departement :)

Thanks for handling this, already uploaded to Debian so it will be in time for the upcoming release.
