### ISSUE TITLE
Retrieve both regular magic and MIME with minimal overhead

### ISSUE THREAD

**Issue by rmspeers** [ahupp/python-magic#181]
This may be an issue with the underlying libmagic, but I'd like to retrieve both the MIME and regular magic string, e.g. 'ASCII text, with no line terminators' and 'text/plain', in a single call.

I'd like to do this without doing searches through the magic database twice, which I know is possible if I just keep two instances of Magic() myself, or if I let the library cache those for me.

Opening this to gather input on if such an improvement is possible from this library's perspective.

**Comment by rmspeers** [comment]
This _may_ be related to https://github.com/ahupp/python-magic/pull/81/files, although I think we could also solve that PR by just changing the elif for flags to an if statement to allow the ORing to stack.

**Comment by ahupp** [comment]
This would be a pretty substantial API change and without changing libmagic would not really be a perf win.  There's probably space for a whole new API for libmagic, but until then I'll close.
