### ISSUE TITLE
When I run magic.from_file() in windowsXP, it can not read the file magic.mgc correctly.

### ISSUE THREAD

**Issue by just-OneKey** [ahupp/python-magic#182]
>>>import magic
>>>file_type = magic.from_file("C:\\nc.exe")
C:\Python27\lib\site-packages\magic\libmagic\magic.mgc, 1: Warning: offset `?' invalid
C:\Python27\lib\site-packages\magic\libmagic\magic.mgc, 6: Warning: offset `Firmware v' invalid
C:\Python27\lib\site-packages\magic\libmagic\magic.mgc, 7: Warning: offset `' invalid
C:\Python27\lib\site-packages\magic\libmagic\magic.mgc, 8: Warning: offset `' invalid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\magic\magic.py", line 134, in from_file
    m = _get_magic_type(mime)
  File "C:\Python27\lib\site-packages\magic\magic.py", line 122, in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
  File "C:\Python27\lib\site-packages\magic\magic.py", line 71, in __init__
    magic_load(self.cookie, magic_file)
  File "C:\Python27\lib\site-packages\magic\magic.py", line 273, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "C:\Python27\lib\site-packages\magic\magic.py", line 204, in errorcheck_negative_one
    raise MagicException(err)
magic.magic.MagicException: cannot stat `C:\Python27\lib\site-packages\magic\libmagic\magic.mgc' (In
valid argument)

My python version is 2.7.15.
I don't know how to fix this problem.

**Comment by ahupp** [comment]
This looks like a problem with your local install of libmagic.  Does that file it's warning about actually exist?

**Comment by just-OneKey** [comment]
Yes, it does exist. Its path is "C:\python27\lib\site-packages\magic\libmagic\magic.mgc".
Here is the screenshot.
![image](https://user-images.githubusercontent.com/42026869/45744128-511b5d00-bc30-11e8-9823-5c113a2a43c5.png)

If this is a problem with the install of libmagic, what should I do to find what's wrong with the install, or what can I do to solve this problem?
This is the information of my system.
![image](https://user-images.githubusercontent.com/42026869/45744403-09e19c00-bc31-11e8-831b-9b05e7500a0e.png)

**Comment by ahupp** [comment]
Unfortunately, this error is coming from inside libmagic.  I haven't seen an installation that puts the magic.mgc in python's site-packages.  Where did you get the binaries?

**Comment by just-OneKey** [comment]
It is automaticly installed. I'm not sure whether it is installed by the command "pip install python-magic" or the installation of python-magic-bin(https://pypi.python.org/pypi/python-magic-bin/0.4.14), which is needed for windows.

**Comment by ahupp** [comment]
Sometimes the Sysinternals Process Monitor (procmon) is useful for debugging these kinds of problems because it can show you what files a process is actually trying to read.  https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by ahupp** [comment]
Note that I don't maintain the -bin package, you may want to file an issue there.

**Comment by just-OneKey** [comment]
All right. Thank you for your help anyway. Wish you the best!

**Comment by ahupp** [comment]
Going to close this since it doesn't seem to be related to this package, but feel free to re-open if something comes up.
