### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by noraj** [ahupp/python-magic#186]
## Description of the issue

StegoVeritas uses python-magic as a dependency. Something broke with python-magic, but since python-magic have no changelog (either a separate file or in the github release history) it is impossible to say if an update in python-magic introduced a breaking change.

## Way to solve

Use a changelog where all version release are documented

## Reference

https://github.com/bannsec/stegoVeritas/issues/10

**Comment by ahupp** [comment]
You can see the full history of changes here:

https://github.com/ahupp/python-magic/commits/master

If there was some significant breaking changes I'd probably call them out more prominently but that never happens.  In this case the problem (as discussed on the other issue) is conflicting names between two different python modules.
