### ISSUE TITLE
Warning when importing magic from latest python3.8

### ISSUE THREAD

**Issue by gabrieldiego** [ahupp/python-magic#187]
Hello,

When importing magic using the latest python3.8, it produces a warning:
```
Python 3.8.0a2+ (heads/master:ed1deb0, Feb 27 2019, 09:39:58) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
/home/gabriel/Projects/python-magic/magic.py:203: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is -1:
>>> 
```
It seems that this warning has been introduced in  2019-Jan-17 with this commit:
[https://github.com/python/cpython/commit/3bcbedc9f1471d957a30a90f9d1251516b422416](https://github.com/python/cpython/commit/3bcbedc9f1471d957a30a90f9d1251516b422416)

I did a quick fix for this issue, which removes the warning and no other warning remains:

```
diff --git a/magic.py b/magic.py
index d027157..bd9d6b4 100644
--- a/magic.py
+++ b/magic.py
@@ -200,7 +200,7 @@ def errorcheck_null(result, func, args):
 
 
 def errorcheck_negative_one(result, func, args):
-    if result is -1:
+    if result == -1:
         err = magic_error(args[0])
         raise MagicException(err)
     else:
```

Regards,
Gabriel

**Comment by ahupp** [comment]
That's a real issue, not sure why I wrote it that way.  Thanks for the patch!
