### ISSUE TITLE
mime type of json is interpretted as 'text/plain'

### ISSUE THREAD

**Issue by can1can** [ahupp/python-magic#193]
Hi,
magic.from_buffer(file.read(),mime=True)  returning text/plain for json file whenever it contains an empty array
Debian GNU/Linux 10
python3.7
python-magic==0.4.15
libmagic==1.0

**Comment by kyprifog** [comment]
I am having a similar issue with CSV being recognized as ASCII Text for Debian GNU/Linux 10, but on mac it gets recognized properly as CSV.

**Comment by ahupp** [comment]
What does `file --mime-type <the json file>` report?  This is probably the behavior of the underlying libmagic library; there are many cases where results are ambiguous.
