### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by Adhders** [ahupp/python-magic#195]
when I import magic on Windows, it shows "Process finished with exit code -1073741819 (0xC0000005)", what is trouble with magic

**Comment by ahupp** [comment]
Sorry, I don't have a windows machine so would have to lean on you to debug this.  It's almost certainly a problem with the libmagic dll rather than python-magic itself.  Googling shows this might be an access violation of some kind.  Do you have a debugger setup?

**Comment by ahupp** [comment]
Closing because it doesn't seem to be a python-magic issue.
