### ISSUE TITLE
custom magic_file format

### ISSUE THREAD

**Issue by janice0324** [ahupp/python-magic#196]
I try to use magic_file but it will show the error below: 

![image](https://user-images.githubusercontent.com/27798650/63903686-ea5a1280-ca40-11e9-9fc6-a0f07948d8c1.png)

and the item in my magic file:
0       string  00000000000000000000000000000000000000000000000000000000000000000 application/Xilinx-ace

how can I resolve this problem.

thanks

**Comment by ahupp** [comment]
It looks like this issue reported against the underlying magic library:

https://github.com/threatstack/libmagic/issues/10

Where did you get this magic file?  My guess is that support for this style of line was added in a later version of the library (of libmagic, not python-magic) than you are using, and you'll need to upgrade.

**Comment by ahupp** [comment]
Closing issue b/c it's in libmagic.
