### ISSUE TITLE
magic.MagicException: could not find any magic files!

### ISSUE THREAD

**Issue by ch3j43** [ahupp/python-magic#20]
Hi,

Getting this error when i try the 
m = magic.Magic(mime=True).

What must be the cause?

Thanks in advance

**Comment by Pysis868** [comment]
Thanks for matt's comment https://github.com/ahupp/python-magic/issues/20#issuecomment-14921259.
For my mac with Homebrew it was in `/usr/local/Cellar/libmagic/5.37/share/misc/magic`.
