### ISSUE TITLE
Expose libmagic.magic_version

### ISSUE THREAD

**Issue by Lucidiot** [ahupp/python-magic#204]
We recently ran into an issue where versions of `libmagic` older than 1.35 did not detect JSON files (and some of our systems had out of date libmagic installs).

The [`magic_version`](https://github.com/file/file/blob/56367e2bbd0d01601a8875879d73cfd652d7206a/src/magic.c#L586) method in libmagic gives an integer for the version number. I believe it could be exposed in the package as `magic.magic_version` in a way similar to [`magic_open`](https://github.com/ahupp/python-magic/blob/4e415a1c1cc5a874e213d1ea02d3050f7d57b8fe/magic.py#L248-L250). We used `magic.libmagic.magic_version` and it worked, but it is probably better to have it properly exposed in the python package.

The package could also have a slightly more complex method to yield a version number using one of the two version classes from [`distutils.version`](https://github.com/python/cpython/blob/3.8/Lib/distutils/version.py), just to make it nicer than an integer.

**Comment by ahupp** [comment]
I've exposed this as magic.version(), returning the bare integer.  I'm wary of trying to parse it because I can't be sure of anything other than the number is increasing.
