### ISSUE TITLE
[Chore] Time for a new release ?

### ISSUE THREAD

**Issue by noraj** [ahupp/python-magic#210]
The last release is from Dec 4, 2017, a lot of fixes where made in between. Time for a new release?

**Comment by ahupp** [comment]
Yeah, I really should get a new release out.  Thanks for the nudge!

**Comment by ahupp** [comment]
New release is up, thanks again!

**Comment by noraj** [comment]
would be nice to make a git tag for 0.4.18 too :smiley: 

![image](https://user-images.githubusercontent.com/16578570/81168994-57db1d00-8f98-11ea-85aa-cf53b7fd7897.png)

**Comment by ahupp** [comment]
I forgot tags don't push by default.  I've pushed 0.4.17 and .18.  Thanks for noticing.
