### ISSUE TITLE
undefined symbol magic_setparam with python-magic==0.4.17

### ISSUE THREAD

**Issue by pembo13** [ahupp/python-magic#211]
The new package doesn't work for me, at least in CentOS 7 and Python 3.6

    $ python -c "import magic"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/virt/proj/lib64/python3.6/site-packages/magic.py", line 304, in <module>
        _magic_setparam = libmagic.magic_setparam
      File "/usr/lib64/python3.6/ctypes/__init__.py", line 356, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib64/python3.6/ctypes/__init__.py", line 361, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /lib64/libmagic.so.1: undefined symbol: magic_setparam

**Comment by ahupp** [comment]
I just pushed a 0.4.18 along with some docker tests that should detect CentOS breakage in the future.  Want to give it a try?

**Comment by mbarakaja** [comment]
Hi @ahupp 

I am not sure if this is related but my build started failing with this new version

```python
h_inventory/fetch.py:131: in _validate
    mimetype = magic.from_buffer(response.content, mime=True)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:165: in from_buffer
    m = _get_magic_type(mime)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:139: in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:76: in __init__
    self.setparam(MAGIC_PARAM_NAME_MAX, 64)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:113: in setparam
    return magic_setparam(self.cookie, param, val)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:322: in magic_setparam
    return _magic_setparam(cookie, param, byref(v))
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/magic.py:217: in errorcheck_negative_one
    raise MagicException(err)
E   MagicException: None
```

I basically check the content type of a HTTP body using this library. My build is still working up to `0.4.15`

**Comment by ahupp** [comment]
Is this Centos7?  I pushed 0.4.18 last night which should fix this.

**Comment by ahupp** [comment]
Which distro and version of libmagic is this?

**Comment by ahupp** [comment]
@mbarakaja I've moved your report to https://github.com/ahupp/python-magic/issues/213.  #211 should be fixed now.
