### ISSUE TITLE
CHANGELOG missing?

### ISSUE THREAD

**Issue by jberends** [ahupp/python-magic#212]
I saw you released a new release to PyPI. Care to tell what has changed in a CHANGELOG.md?

We use this code in a production setup and it is always. Nice to understand the impact of changes. Thanks for the library!

**Comment by ahupp** [comment]
Good call, you aren't the first person to request it.  I've written one for .17 and .18 here:

https://github.com/ahupp/python-magic/blob/master/CHANGELOG
