### ISSUE TITLE
s3cmd fails

### ISSUE THREAD

**Issue by gisraeliyotpo** [ahupp/python-magic#214]
Hi yesterday my travis build failed on s3cmd after investigating it was the new version of your library this is the error i got:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Invoked as: /home/travis/.local/bin/s3cmd sync s3://my-folder/folder/ /folder/folder/ -r -v --delete-removed -q
Problem: MagicException: None
S3cmd:   2.1.0
python:   2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4]
environment LANG=en_US.UTF-8
Traceback (most recent call last):
  File "/home/travis/.local/bin/s3cmd", line 3102, in <module>
    from S3.S3 import S3
  File "/home/travis/.local/lib/python2.7/site-packages/S3/S3.py", line 56, in <module>
    magic_ = magic.Magic(mime=True)
  File "/home/travis/.local/lib/python2.7/site-packages/magic.py", line 76, in __init__
    self.setparam(MAGIC_PARAM_NAME_MAX, 64)
  File "/home/travis/.local/lib/python2.7/site-packages/magic.py", line 113, in setparam
    return magic_setparam(self.cookie, param, val)
  File "/home/travis/.local/lib/python2.7/site-packages/magic.py", line 322, in magic_setparam
    return _magic_setparam(cookie, param, byref(v))
  File "/home/travis/.local/lib/python2.7/site-packages/magic.py", line 217, in errorcheck_negative_one
    raise MagicException(err)
MagicException: None
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

moved back to old version

**Comment by ahupp** [comment]
Can you tell me what distro/libmagic version this is?

**Comment by gisraeliyotpo** [comment]
sorry i don't know which one
it was configured to take the last version of the lib

**Comment by ahupp** [comment]
I believe this is fixed in 1b6cede2550784251296496ad65ece8266e56250.  Can you verify?

**Comment by ahupp** [comment]
This is old and believed fixed, please reopen if you still have an issue
