### ISSUE TITLE
wrong detection of docx and xlsx

### ISSUE THREAD

**Issue by ayeteng** [ahupp/python-magic#217]
python-magic==0.4.18

Try to get the mime type of docx and xlsx with following code:

`mime_type = magic.from_buffer(file_buffer[:2048], mime=True)`

both files are recognized 'application/zip'

[test.xlsx](https://github.com/ahupp/python-magic/files/4699451/test.xlsx)
[test.docx](https://github.com/ahupp/python-magic/files/4699452/test.docx)

Any suggestion?

**Comment by ayeteng** [comment]
https://serverfault.com/questions/338087/making-libmagic-file-detect-docx-files/377792#377792

Add customized magic solve the issue.

**Comment by jantonio471** [comment]
Hi every body, 

I can't solver this issue in CentOS 7, but I install the new version of the `file` package and It works, leve the comment where I explain this solution.

https://github.com/mckinseyacademy/django-upload-validator/issues/15#issuecomment-697099479
