### ISSUE TITLE
List of extensions detectable by python-magic?

### ISSUE THREAD

**Issue by CloudKai** [ahupp/python-magic#228]
Hi, I am very new to this and would like to know if there's a list of file extensions that I could refer to? Or do I assume it can detect every file extensions? Thanks!

**Comment by ahupp** [comment]
python-magic is a wrapper around the C library libmagic, and the database of definitions it ships with.  That database is ever changing, so depending on what version of libmagic you use you'll get a bigger or smaller list.  However, the set is very comprehensive so it should recognize any reasonably popular file format.  

If you literally mean the feature where it returns the suggested extension (e.g an image/jpeg -> .jpg), that's pretty new and I'm not sure what exact files libmagic supports, by in my limited testing it wasn't very comprehensive.
