### ISSUE TITLE
AttributeError: Symbol not found: magic_open in Release 0.4.20

### ISSUE THREAD

**Issue by anushbmx** [ahupp/python-magic#232]
There is an error in new release 0.4.20 'AttributeError: Symbol not found: magic_open'
```
File "/usr/local/lib/python3.7/site-packages/magic/compat.py", line 64, in <module>
    _open = _libraries['magic'].magic_open
```

Quick fix is to use version `0.4.18`

**Comment by ynerant** [comment]
Same issue

**Comment by amir5121** [comment]
I have the same issue.. probably related to [commit](https://github.com/ahupp/python-magic/commit/15b85a280cb267123d01ef61a672a0e38471e7be)

**Comment by ahupp** [comment]
Ah I see.  The compat layer doesn't have all the same logic for finding the DLL that the top-level library has.  Will fix.

**Comment by artemistomaras** [comment]
Same issue here. Reverting to 0.4.18

**Comment by ahupp** [comment]
Fixed in b520bf0bf6f815afad33878ecdbe4b1d907dcc94 / 0.4.21.  Thanks for the report!

**Comment by ahupp** [comment]
@anushbmx @ynerant, I should mention that I wasn't able to reproduce this issue in a docker image w/ alpine:latest.  Could you verify 0.4.21 fixes it for you?

**Comment by anushbmx** [comment]
@ahupp Will update you once I retry with new version.
