### ISSUE TITLE
When will pypi have the latest version (currently 0.4.18) 

### ISSUE THREAD

**Issue by jrmarino** [ahupp/python-magic#234]
https://pypi.org/project/python-magic/ is currently at 0.4.18
The last tag (0.4.20) was released 27 days ago.
When might one expect pypi to reflect the latest tag?
I'm asking as a packager (http://www.ravenports.com/)

**Comment by yochananmarqos** [comment]
0.4.19 & 0.4.20 were ["yanked"](https://pypi.org/project/python-magic/#history), but still [available](https://pypi.org/project/python-magic/0.4.20/#files) on PyPI. Not sure why.

**Comment by jrmarino** [comment]
okay, thanks.  So I can assume there will be a 0.4.21 "soon" that will appear on pypi?

**Comment by yochananmarqos** [comment]
Don't know, you'd have to ask @ahupp about that.

**Comment by ahupp** [comment]
I yanked 0.4.20 because of #232.  I've fixed that issue and released 0.4.21.
