### ISSUE TITLE
Type annotations missing on PyPI

### ISSUE THREAD

**Issue by bexnoss** [ahupp/python-magic#258]
The [python-magic-0.4.24.tar.gz](https://files.pythonhosted.org/packages/3a/70/76b185393fecf78f81c12f9dc7b1df814df785f6acb545fc92b016e75a7e/python-magic-0.4.24.tar.gz) file on PyPI is missing the `magic/__init__.pyi` file.

**Comment by ahupp** [comment]
Thanks, this is fixed in 0.4.25
