### ISSUE TITLE
magic.from_buffer is returning 'application/csv' for CSV files instead of 'text/csv'

### ISSUE THREAD

**Issue by CHelfgott** [ahupp/python-magic#263]
The latter is the correct MIME type according to RFC 7111, and I know for a fact that magic returned 'text/csv' at some point in the past (although I have not rolled back my installation to check which version did so).

**Comment by ahupp** [comment]
The mime type returned is determined by the underlying libmagic installation rather than python-magic.  I'd compare with what the `file` command returns, and check the version of the install.

**Comment by CHelfgott** [comment]
thank you, I eventually twigged to that myself.
