### ISSUE TITLE
Image file being reported as "text/plain"

### ISSUE THREAD

**Issue by shoenig** [ahupp/python-magic#29]
Linux's file command reports:

[moonstone Desktop] ‽ file dino.png
dino.png: PNG image data, 492 x 639, 8-bit colormap, non-interlaced

However, magic is reporting the mime type as "text/plain"

The image:

![dino](https://f.cloud.github.com/assets/394887/246925/caeb89b8-8ab6-11e2-9b9b-a5c7b2efe7bb.png)

**Comment by ahupp** [comment]
Thanks for the followup!
