### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by TheNoShade** [ahupp/python-magic#313]
I have docker based python project. When trying to import **magic** and up my container I'm facing below error

`File "/usr/local/lib/python3.11/site-packages/magic/loader.py", line 49, in load_lib
raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

When I'm trying to install **python-libmagic** below error occurred

`error: command '/usr/bin/gcc' failed with exit code 1
[end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
Successfully built python-libmagic
Failed to build cffi
ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects`

I tried many things but all in vain. Please help to solve this issue. Thanks.

**Comment by ddelange** [comment]
Hi @TheNoShade 👋

- [python-libmagic](https://pypi.org/project/python-libmagic/) is a different (abandoned) project
- [python-magic](https://pypi.org/project/python-magic/) (this project) currently requires you to `apt-get install libmagic1` (see README) before this project becomes usable. 
  - A PR to fix this is open: https://github.com/ahupp/python-magic/pull/294

**Comment by ahupp** [comment]
Yes, ^^ that's true.  Too many similarly named packages unfortunately.
