### ISSUE TITLE
Unicode file name issue on windows

### ISSUE THREAD

**Issue by pombredanne** [ahupp/python-magic#42]
This is the same as https://github.com/ahupp/python-magic/issues/9
BUT I cannot encode to utf-8 as I do not know which encoding was used to create that filename. The file was created on some linux and is extracted on windows.

A test file is in this archive: https://github.com/pombredanne/python-magic/blob/issue_42/testdata/a.zip

When extracted on windows I can os.walk or os.listdir(u'some dir') (using a unicode string for the input dir) where this file has been extracted and open the file in Python alright. ie os.path.exists is True and the file can be opened.

Yet magic.from_file fails when passing the filename whether as a string or unicode

The point being that you cannot rely on my file system encoding to convert the file name, because it was created elsewhere, and the encoding is arbitrary, eventually unknown.

The best explanation of the problem is here IMHO: http://web.archive.org/web/20081219193532/http://boodebr.org/main/python/all-about-python-and-unicode#UNI_FILENAMES

NB: FWIW, I cannot get run the file command line to work on that path either... so it could be a problem with the file code itself, not your ctypes wrapper

**Comment by PhobosK** [comment]
Since this is a real issue (fixed now), but was committed way after the last available official release (even the one here 0.4.3), would you please consider preparing a recent release with this and all other fixes you have added since 2012 ?

**Comment by ahupp** [comment]
Yeah, the release schedule has been poky. I just pushed 0.4.7 which is up-to-date.
