### ISSUE TITLE
I'm the Gentoo maintainer for eyeD3 (python)

### ISSUE THREAD

**Issue by ssuominengentoo** [ahupp/python-magic#57]
I'm the Gentoo maintainer for eyeD3 python module:
http://eyed3.nicfit.net/
It seems that the new 0.7.4 version uses this python-magic module which is in fact a direct conflict with the python-magic version that has been a stable API for years, file-5.17's magic.py:
http://www.darwinsys.com/file/
so now some packages can no longer co-exist on the same system:
https://bugs.gentoo.org/show_bug.cgi?id=488270

While this project is still young, can you please rename the library, to, for example, magic2 as to imply this is the continuity of the prev. library if you are in fact sure the magic.py from *the* file package that is installed on every *nix system is obsolete/no longer maintained, which is suspect it's not
I don't remember seeing any bugs about it, only use:
https://github.com/pazz/alot (alot mail client uses file's magic.py)
http://code.google.com/p/binwalk/ (tool identifying files embedded inside firmware images also uses file's magic)
Sabayon Linux distributions *package manager* equo uses file's magic.py:
http://www.sabayon.org

Please :)

**Comment by ahupp** [comment]
dupe #33
