### ISSUE TITLE
can not find libmagic  in mingw environment

### ISSUE THREAD

**Issue by yiwiz-sai** [ahupp/python-magic#60]
libname = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1')

should add
ctypes.util.find_library('msys-magic-1.dll')

**Comment by abakum** [comment]
https://github.com/ahupp/python-magic/pull/189

**Comment by ahupp** [comment]
Merging into https://github.com/ahupp/python-magic/issues/293
