### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by tomek-he-him** [ahupp/python-magic#61]
I get the above error on Windows 8.1 x64 using either Git Bash, Cygwin or the regular Command Line.

A similar issue has been posted as #12, but the solution there was to install libmagic. I have the package properly installed:

```
> where file
c:\cygwin64\bin\file.exe
```

**Comment by Charan29** [comment]
@ahupp, please suggest me how i can resolve this issue
>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\mag
    from magic.identify import Magic, Mag
  File "C:\Python34\lib\site-packages\mag
    from magic import api
  File "C:\Python34\lib\site-packages\mag
    raise ImportError('Unable to find mag
ImportError: Unable to find magic library

i am using window7 32-bit system and i have download mentioned .dll files and given PATH in environment option.

**Comment by ahupp** [comment]
@Charan29 sorry, i'm not sure how to debug that.  I suggest using a tool like procmon to see where it's looking for the DLLs
