### ISSUE TITLE
Why the result isn't the same?

### ISSUE THREAD

**Issue by shiyanhui** [ahupp/python-magic#63]
In terminal `file --mime-type 1.mp3`, and the result is "audio/mpeg". 

But with python-magic, it's this:

```
>>> magic.from_file('1.mp3', mime=True)
>>> application/octet-stream
```

Why the result is not the same?

**Comment by kirthiprakash** [comment]
I too face the same issue with *.AMR files. With mime=False, its outputs the human readable form 'Adaptive Multi-Rate Codec (GSM telephony)'. And with mime=True the output is 'application/octet-stream'. 

Is there a mapping table where I can add a new rule for the above case?

**Comment by Lewiscowles1986** [comment]
I'm getting the same for `Audio file with ID3 version 2.3.0`
