### ISSUE TITLE
How to get charset?

### ISSUE THREAD

**Issue by yangjuven** [ahupp/python-magic#69]
Using those code can only get mime `image/jpeg` without charset.

``` python
import magic

#1
magic.from_file('test.jpg', mime=True)

#2
magic.from_buffer(open('test.jpg').read(1024), mime=True)

#3
magic.Magic(mime=True, mime_encoding=True).from_file('test.jpg')
```

But command `file --mime test.jpg` will print `test.jpg: image/jpeg; charset=binary`. How to get the charset?

**Comment by ahupp** [comment]
Fixed in 74e87c5ace821d0a3e5fce725ae661d57889ae47.  The default when using from_[buffer|file](..., mime=True) will be MAGIC_MIME_TYPE, but anyone using the MAGIC_MIME constant will get the new value.
