### ISSUE TITLE
Problem on ELF 64bit

### ISSUE THREAD

**Issue by dummys** [ahupp/python-magic#71]
Hello,

I get the following error using the last python-magic.

magic.MagicException: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linkederror reading (Invalid argument)

**Comment by ahupp** [comment]
There is nowhere near enough information in this issue report to help you with your problem.

**Comment by dummys** [comment]
I only run it on a ELF 64 bit and go this problem. Can't figure it out.

**Comment by pombreda** [comment]
@dummys could you submit a test file and a snippet of code with details of which environment/os/libmagic version you used?
