### ISSUE TITLE
Python-magic reporting inaccurate MIME types

### ISSUE THREAD

**Issue by jamiesonbecker** [ahupp/python-magic#75]
Python-magic is sometimes providing incorrect values for HTML and CSS files (among others). Original downstream issue and code to reproduce: https://github.com/s3tools/s3cmd/issues/198#issuecomment-21835205

Does this look like an upstream (libmagic) bug, possibly w/ Debian/Ubuntu packaging?

**Comment by traviscollins** [comment]
I believe it is an upstream bug. 

[root@localhost css]# file -i main-style.css
*main-style.css: text/x-c++; charset=us-ascii*
[root@ localhost css]# cat /etc/redhat-release 
CentOS release 6.6 (Final)

**Comment by jamiesonbecker** [comment]
Good catch. and it's clearly across distributions.

New bug: https://github.com/threatstack/libmagic/issues/1

**Comment by ahupp** [comment]
Yeah, looks like a libmagic issue.
