### ISSUE TITLE
WindowsError: exception: access violation writing 0x00000000

### ISSUE THREAD

**Issue by Disassem** [ahupp/python-magic#76]
I used cygmagic-1.dll from Cygwin package "file-5.22-1" (of course, with all dependent dlls) on Windows 7 x64. `python-magic` lastest from master.

test.py
```python
import magic

magic_detect = magic.Magic()
```
Result:
```python
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    magic_detect = magic.Magic()
  File "D:\Spirit\Development\Python\IIS\RemoveUnnecessaryFiles\magic.py", line 59, in __init__
    self.cookie = magic_open(self.flags)
WindowsError: exception: access violation writing 0x00000000
Exception AttributeError: "Magic instance has no attribute 'cookie'" in <bound method Magic.__del__ of <magic.Magic instance at 0x024058F0>> ignored
```

**Comment by ahupp** [comment]
Unfortunately this is not something I can debug, as I don't have a windows machine.  My best guess is that this is an issue with the ctypes binding in this particular dll build.  You can also try writing a trivial C program against these dlls and see if they work outside of python.

**Comment by Disassem** [comment]
At least these DLLs work fine with file.exe from the same package ("file-5.22-1"). DLLs from package "file-5.20-1" also doesn't work with python. Thank you for answer. I'll try something more.

**Comment by aronadaal** [comment]
@Disassem Did you find a solution? I got the same problem here...

**Comment by Disassem** [comment]
@aronadaal No

**Comment by tritium21** [comment]
Have you tried using [File for Windows](http://gnuwin32.sourceforge.net/packages/file.htm) instead of Cygwin?

**Comment by Disassem** [comment]
@tritium21 Yes, I used it. But it is too old (last version is 5.03) and its signatures is too old. And signatures from new versions doesn't compatible with old versions.

**Comment by aronadaal** [comment]
Ok, I have some news to this :)
The bug results because we're mixing Windows-Python and Cygwin. So after deinstalling Windows-Python and installing Cygwin's Python everything is fine.

see https://cygwin.com/ml/cygwin/2016-01/msg00135.html

btw. Corinna updated the Cygwin's file package to 5.25

@ahupp Could you please add the bug & solution to the Troubleshooting guide?

**Comment by Disassem** [comment]
@aronadaal Thanks

**Comment by ahupp** [comment]
thanks, I've updated the troubleshooting section: https://github.com/ahupp/python-magic/blob/master/README.md
