### ISSUE TITLE
OSX format's recognized as "inode/directory"

### ISSUE THREAD

**Issue by 4nc3str4l** [ahupp/python-magic#79]
I have tried to recognize files of type:
- pages
- keynote 
- numbers  

And returns always "inode/directory".

Thanks for your time, your library is very cool and usefull :)

**Comment by ahupp** [comment]
That's odd.  What does the `file` command return for those?  Ideally you'd try using the same file build that python-magic is using.

**Comment by ahupp** [comment]
But in general all the filetype decisions are made by libmagic and not in the python wrapper.

**Comment by ahupp** [comment]
Closing due to lack of response, but this is probably the underling libmagic library.
