### ISSUE TITLE
Allowing more keyword arguments for magic.from_buffer()/magic.from_file()

### ISSUE THREAD

**Issue by Ecno92** [ahupp/python-magic#80]
I just came across this package and I saw that `magic.from_buffer()` and `magic.from_file()` only accept the keyword argument `mime` while the Magic class accepts more arguments like for instance `keep_going`. 

I did not do a extensive check on the internals yet, but why are the other keyword arguments of the Magic class not implemented in the functions? It would be nice to be able to use them.

**Comment by ahupp** [comment]
The intent is that the from_buffer/from_file methods are for simple, common calls, and you can create an instance of Magic with other params if you really wanted to.  Its certainly possible to add the keyword params for the rest of them but then it makes the memoization of the Magic instance more complicated.
