### ISSUE TITLE
Multiple threads issue in Flask

### ISSUE THREAD

**Issue by HackerMD** [ahupp/python-magic#85]
When I call `magic.from_file()` within my Flask application (with flask_uwsgi_bwebsocket) I get the following error:

```
File "./api.py", line 60, in build_html_figure_string
    if re.match(r'HTML', magic.from_file(filename)):
  File "/Users/mdh/Envs/tmaps/lib/python2.7/site-packages/magic.py", line 120, in from_file
    return m.from_file(filename)
  File "/Users/mdh/Envs/tmaps/lib/python2.7/site-packages/magic.py", line 73, in from_file
    self._thread_check()
  File "/Users/mdh/Envs/tmaps/lib/python2.7/site-packages/magic.py", line 81, in _thread_check
    raise Exception('attempting to use libmagic on multiple threads will '
Exception: attempting to use libmagic on multiple threads will end in SEGV.  Prefer to use the module functions from_file or from_buffer, or carefully manage direct use of the Magic class
<Greenlet at 0x1151845f0: listen(<flask_uwsgi_websocket._gevent.GeventWebSocketClie)> failed with Exception
```

I'm confused about the error message, because I already use the module function `from_file` as recommended.

**Comment by ahupp** [comment]
I think you have a global instance of magic.Magic() that is shared across threads.  This is not safe due to the underlying libraries implementation.  You'll either need to create a new instance of Magic for each thread, or use the module-level function `magic.from_file` which handles this for you.
