### ISSUE TITLE
Return str on python3 instead of bytes

### ISSUE THREAD

**Issue by zelo** [ahupp/python-magic#86]
I'm using python-magic==0.4.6 on both python 2 and 3.
It looks like there is inconsistency with returned type across those versions.
I'm wondering if this is on purpose?

```
import magic
mime = magic.Magic(mime=True)

result = mime.from_file('whatever.xml')
print("{type}: {mime}".format(type=type(result), mime=result))
```
`python2`  => `<type 'str'>, inode/x-empty`
`python3`=> `<class 'bytes'>, b'inode/x-empty'`

EDIT:
Sorry i missed #52 while searching.

**Comment by ahupp** [comment]
They are actually the "same" type, in the sense that python2's str played double-duty as both a human readable string and a bag of bytes.
