### ISSUE TITLE
Jar file are shown as application/jar instead of application/java-archive

### ISSUE THREAD

**Issue by eplaut** [ahupp/python-magic#88]
```
$ grep jar /etc/mime.types
application/java-archive			jar

In [4]: magic.from_file('/usr/share/java/unoloader.jar', mime=True)
Out[4]: 'application/jar'
```

Thanks,
Eli

**Comment by ahupp** [comment]
libmagic does not use /etc/mime.types as far as I know.

**Comment by eplaut** [comment]
I don't know how libmagic works. but python standard library mimetypes does, and application/ jar is unknown mime (i tried to search for it in Google) 
Should i open it in libmagic repo?

thanks

**Comment by ahupp** [comment]
I get "application/zip" on every system I used (osx, CentOS, debian) from both `file --mime` and magic.from_file(..., mime=True).  I think this issue us due to the configuration of the magic files on your system.
