### ISSUE TITLE
UnicodeDecodeError on pip install with version 0.4.7

### ISSUE THREAD

**Issue by mjsilva** [ahupp/python-magic#89]
Hi,

We're facing a issue when trying to install thumbor using python-magic version 0.4.7 via pip. Not sure if it's related to python-magic itself or something else, but when I rollback to version 0.4.6 thumbor installs without an issue.

Here's pip log: https://gist.github.com/mjsilva/4d43075e707f999c3c42

Could this be related to recent changes done [here](https://github.com/ahupp/python-magic/compare/a051eae3ebc7a5555cb32ca8b99ffb099b5a19da...56871b5941899f5cc102832e08016301a46823a6#diff-d5ee5690de230236aca3ced1e8b15f0bR197)?

Appreciate your help. Feel free to ask more debug questions, I can replicate the issue by switching between python-magic versions.

Thanks!

**Comment by OndroNR** [comment]
Hi, same issue with `s3cmd`.

**Comment by artem-cliqz** [comment]
Same issue

**Comment by theist** [comment]
Same installing `s3cmd` 

Doing `LC_ALL=C pip install python-magic` seems to workarround it, al least for Python 2.7.6 in an Ubuntu 14.04.3 LTS using Linux ip-172-31-5-140 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux kernel

**Comment by ahupp** [comment]
Thanks for the report.  I think what happened is that it's including tests in the distribution now, which adds a non-ascii filename.  I can't reproduce the problem on either of my machines, but I've put up a 0.4.8 that removes the test directory.  Can someone see if they repro?

**Comment by ahupp** [comment]
@theist @artem-cliqz @OndroNR @mjsilva : are you still seeing this with 0.4.8?

**Comment by mjsilva** [comment]
Hi @ahupp thanks for jumping on this.

Weirdly I still have the same issue with 0.4.8, see pip.log: https://gist.github.com/mjsilva/9fba1a72a969fd16c7ce

Our linux version
````
Linux imgxx-i-7764dda8.example.com 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
````

Python version: ```` Python 2.7.6 ````

Anything else I can provide to help out the debug?

**Comment by tk421** [comment]
Problem still happens

    Downloading/unpacking python-magic>=0.4.3 (from thumbor)
      Downloading python-magic-0.4.8.tar.gz (132kB): 132kB downloaded
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
        do_download,
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
        self.session,
      File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
        unpack_file(temp_location, location, content_type, link)
      File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
        untar_file(filename, location)
      File "/usr/lib/python2.7/dist-packages/pip/util.py", line 574, in untar_file
        path = os.path.join(location, fn)
      File "/usr/lib/python2.7/posixpath.py", line 80, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)

You have here available the [instructions to reproduce the problem](https://manageacloud.com/configuration/thumbor)

You can replicate the problem from [here](https://manageacloud.com/configuration/deploy/testing/thumbor/autostart)

**Comment by mjsilva** [comment]
Bit more debugging....

If I install python-magic manually it seems to work:

```` 
[09:34:12] [staging-miderspan] root@imgxx-i-7764dda8:~# pip freeze | grep magic
[09:34:15] [staging-miderspan] root@imgxx-i-7764dda8:~# pip install python-magic
Downloading/unpacking python-magic
  Downloading python-magic-0.4.8.tar.gz (132kB): 132kB downloaded
  Running setup.py (path:/tmp/pip_build_root/python-magic/setup.py) egg_info for package python-magic

Installing collected packages: python-magic
  Running setup.py install for python-magic

Successfully installed python-magic
Cleaning up...
[09:34:31] [staging-miderspan] root@imgxx-i-7764dda8:~# pip freeze | grep magic
python-magic==0.4.8
[09:34:38] [staging-miderspan] root@imgxx-i-7764dda8:~# /usr/bin/pip install -q https://github.com/thumbor/thumbor/archive/5.0.3.tar.gz#egg=thumbor
````

**Comment by ahupp** [comment]
Sigh, the last change didn't actually filter out this directory.  Try again with 0.4.9.  I've verified that `sdist` no longer reports this file is being included.

**Comment by tk421** [comment]
It is working for me ([last build](https://manageacloud.com/configuration/thumbor/build/22267836)).

**Comment by mjsilva** [comment]
Working for me too. Thanks @ahupp 

Btw @wyrfel did some further debugging and to quote him:

> I had a bit more of a look last night and the actual issue is in pip itself
> pip does in fact uses a python tar module to untar and the code that runs that does the call to os.path.split(), which due to the lambda-file in the test suite causes the error
> also did some simple tests on the server and never managed for it to take the locale settings into account
> it always remained in ansi/ascii mode
> even by setting PYTHONIOENCODING=utf8

**Comment by ahupp** [comment]
Thanks all, and sorry for the breakage.

**Comment by OndroNR** [comment]
Works for me as well. For some reason, I can't simulate installation fail by forcing faulty version. `pip install python-magic==0.4.7 s3cmd` log:
```
Downloading/unpacking python-magic==0.4.7
  Running setup.py (path:/tmp/pip-build-mbR4_F/python-magic/setup.py) egg_info for package python-magic

    'test/testdata/λ' not ANSI_X3.4-1968 encodable -- skipping
Downloading/unpacking s3cmd
  Running setup.py (path:/tmp/pip-build-mbR4_F/s3cmd/setup.py) egg_info for package s3cmd
    Using xml.etree.ElementTree for XML processing

Downloading/unpacking python-dateutil (from s3cmd)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/dist-packages (from python-dateutil->s3cmd)
Installing collected packages: python-magic, s3cmd, python-dateutil
  Running setup.py install for python-magic

    'test/testdata/λ' not ANSI_X3.4-1968 encodable -- skipping
    'test/testdata/λ' not ANSI_X3.4-1968 encodable -- skipping
  Running setup.py install for s3cmd
    Using xml.etree.ElementTree for XML processing
    changing mode of build/scripts-2.7/s3cmd from 644 to 755

    changing mode of /usr/local/bin/s3cmd to 755
Successfully installed python-magic s3cmd python-dateutil
```

I hoped I could provide faulty Dockerfile for testing purposes:
```
FROM node:0.12

# install s3cmd
RUN apt-get update && \
    apt-get install -y python-pip && \
    apt-get clean && \
    apt-get purge

RUN pip install python-magic==0.4.7 s3cmd

CMD ["bash"]
```
