### ISSUE TITLE
Why do functions return bytes rather than strings in python 3

### ISSUE THREAD

**Issue by keisetsu** [ahupp/python-magic#98]
It seems like this should return strings for mime content:
```    content_type = magic.from_buffer(attachment_file, mime=True)```

However, it returns bytes, which must be decoded. I believe this is because of the way output from libmagic is handled in python 3, but it seems like it would make sense to add a decode step

**Comment by ahupp** [comment]
I agree it would probably make more sense to return str in this case.  However, it would be a breaking change.  I'll take a look at this if I introduce a set of breaking changes.

**Comment by pkMyt1** [comment]
This is a Python 3 feature.  Doesn't have to be decoded, just explicitly return a string.
content_type = str(magic.from_buffer(attachment_file, mime=True))

**Comment by ztane** [comment]
The Python 3 code could be made to return `str` alright, and should ASAP. I'd prefer:

    try:
         decoded = b.decode('utf-8')
    except UnicodeError:
         decoded = b.decode('iso8859-1')

as for a breaking change, this would silently break code that uses `ctype == b'text/html'`, but would loudly complain on any code that uses `startswith` or pattern matching or so.

**Comment by ahupp** [comment]
Fixed in b166698

**Comment by ztane** [comment]
Just a stylistic one, but rather than `if`fing inside a function, you should `if` 2 function definitions.

**Comment by varnion** [comment]
when will this change be pushed to pypi?

**Comment by ahupp** [comment]
pushed.
